In [3]:
import pandas as pd

claims = pd.read_csv("claims_preprocessed_v1.csv")

In [4]:
claims

,Claim_Form_Type,Provider_Specialty,Payer,Place_of_Service_Code,Place_of_Service_Desc,Diagnosis_Code,Procedure_Code,Procedure_Desc,Modifier_Code,Billed_Amount,...,Eligibility_Verified,Duplicate_Claim_Flag,NCCI_Bundling_Flag,Clearinghouse_Validation_Passed,Provider_Monthly_Claim_Volume,Provider_Payer_Prior_Denial_Count,Chronic_Condition_Flag,Claim_Status,CARC_Code,Denial_Reason
0,837P,Orthopedics,Medicare,23,Emergency Room,I10,29881,Knee arthroscopy/surgery,No_Modifier,3796.96,...,True,False,False,True,80,3,False,Approved,NaN,NaN
1,837I,Internal Medicine,Medicaid,21,Inpatient Hospital,J18.9,36415,Blood draw,76,27.95,...,True,False,False,True,257,1,False,Approved,NaN,NaN
2,837P,Radiology,Medicaid,11,Office,E78.5,99213,"Office visit, low complexity",No_Modifier,141.00,...,True,False,False,True,135,2,True,Approved,NaN,NaN
3,837I,Orthopedics,Aetna,22,Outpatient Hospital,M54.5,93000,EKG,No_Modifier,135.13,...,True,False,False,True,290,2,True,Denied,CO-45,Charge exceeds fee schedule/contracted amount
4,837I,Orthopedics,Medicare,21,Inpatient Hospital,K21.9,99213,"Office visit, low complexity",No_Modifier,180.85,...,True,False,False,True,187,2,False,Approved,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,837I,Neurology,Self-Pay,22,Outpatient Hospital,N39.0,72148,MRI lumbar spine,59,1905.88,...,True,False,False,True,151,0,True,Approved,NaN,NaN
14996,837P,Neurology,Self-Pay,23,Emergency Room,E78.5,71046,Chest X-ray,No_Modifier,104.37,...,True,False,False,True,111,0,False,Approved,NaN,NaN
14997,837I,Orthopedics,BCBS,21,Inpatient Hospital,I10,36415,Blood draw,GT,24.32,...,False,False,True,True,46,1,False,Denied,CO-45,Charge exceeds fee schedule/contracted amount
14998,837P,Dermatology,UnitedHealthcare,11,Office,I10,93000,EKG,No_Modifier,98.04,...,True,False,False,True,143,2,False,Approved,NaN,NaN
14999,837I,General Practice,Medicare,22,Outpatient Hospital,M17.0,29881,Knee arthroscopy/surgery,GT,5639.79,...,True,False,False,True,218,4,False,Denied,CO-50,Not deemed a medical necessity

## converting date of submission nd dos

In [5]:
# Convert date columns to datetime
claims["Service_Date"] = pd.to_datetime(claims["Service_Date"])
claims["Claim_Submission_Date"] = pd.to_datetime(claims["Claim_Submission_Date"])

# Extract month
claims["Service_Month"] = claims["Service_Date"].dt.month
claims["Submission_Month"] = claims["Claim_Submission_Date"].dt.month

# Extract day of week
claims["Service_DayOfWeek"] = claims["Service_Date"].dt.dayofweek
claims["Submission_DayOfWeek"] = claims["Claim_Submission_Date"].dt.dayofweek

# Calculate claim submission delay
claims["Claim_Submission_Delay"] = (
    claims["Claim_Submission_Date"] - claims["Service_Date"]
).dt.days

In [6]:
claims[
    [
        "Service_Date",
        "Claim_Submission_Date",
        "Service_Month",
        "Submission_Month",
        "Service_DayOfWeek",
        "Submission_DayOfWeek",
        "Claim_Submission_Delay"
    ]
].head()

,Service_Date,Claim_Submission_Date,Service_Month,Submission_Month,Service_DayOfWeek,Submission_DayOfWeek,Claim_Submission_Delay
0,2023-07-05,2023-07-14,7,7,2,4,9
1,2023-05-18,2023-05-25,5,5,3,3,7
2,2023-08-08,2023-08-11,8,8,1,4,3
3,2023-02-05,2023-02-17,2,2,6,4,12
4,2024-03-19,2024-03-27,3,3,1,2,8

In [7]:
claims["Claim_Submission_Delay"].describe()

count    15000.000000
mean        22.716333
std         44.148943
min          0.000000
25%          3.000000
50%          9.000000
75%         20.000000
max        304.000000
Name: Claim_Submission_Delay, dtype: float64

In [8]:
claims.to_csv("claims_preprocessed_v2.csv", index=False)