In [10]:
import pandas as pd
import joblib

claims = pd.read_csv("claims_preprocessed_v3.csv")

claims.head()

,Claim_Form_Type,Provider_Specialty,Payer,Place_of_Service_Code,Place_of_Service_Desc,Diagnosis_Code,Procedure_Code,Procedure_Desc,Modifier_Code,Billed_Amount,...,Provider_Payer_Prior_Denial_Count,Chronic_Condition_Flag,Claim_Status,CARC_Code,Denial_Reason,Service_Month,Submission_Month,Service_DayOfWeek,Submission_DayOfWeek,Claim_Submission_Delay
0,1,5,4,23,Emergency Room,4,29881,Knee arthroscopy/surgery,4,3796.96,...,3,False,Approved,NaN,NaN,7,7,2,4,9
1,0,3,3,21,Inpatient Hospital,7,36415,Blood draw,2,27.95,...,1,False,Approved,NaN,NaN,5,5,3,3,7
2,1,7,3,11,Office,1,99213,"Office visit, low complexity",4,141.00,...,2,True,Approved,NaN,NaN,8,8,1,4,3
3,0,5,0,22,Outpatient Hospital,10,93000,EKG,4,135.13,...,2,True,Denied,CO-45,Charge exceeds fee schedule/contracted amount,2,2,6,4,12
4,0,5,4,21,Inpatient Hospital,8,99213,"Office visit, low complexity",4,180.85,...,2,False,Approved,NaN,NaN,3,3,1,2,8

## Create the Feature Matrix (X)

In [2]:
drop_columns = [
    "Claim_Status",
    "CARC_Code",
    "Denial_Reason",
    "Procedure_Desc",
    "Place_of_Service_Desc",
    "Service_Date",
    "Claim_Submission_Date"
]

X = claims.drop(columns=drop_columns)

In [4]:
X

,Claim_Form_Type,Provider_Specialty,Payer,Place_of_Service_Code,Diagnosis_Code,Procedure_Code,Modifier_Code,Billed_Amount,Payer_Timely_Filing_Limit_Days,Prior_Auth_Required,...,NCCI_Bundling_Flag,Clearinghouse_Validation_Passed,Provider_Monthly_Claim_Volume,Provider_Payer_Prior_Denial_Count,Chronic_Condition_Flag,Service_Month,Submission_Month,Service_DayOfWeek,Submission_DayOfWeek,Claim_Submission_Delay
0,1,5,4,23,4,29881,4,3796.96,365,True,...,False,True,80,3,False,7,7,2,4,9
1,0,3,3,21,7,36415,2,27.95,180,False,...,False,True,257,1,False,5,5,3,3,7
2,1,7,3,11,1,99213,4,141.00,180,False,...,False,True,135,2,True,8,8,1,4,3
3,0,5,0,22,10,93000,4,135.13,90,False,...,False,True,290,2,True,2,2,6,4,12
4,0,5,4,21,8,99213,4,180.85,365,False,...,False,True,187,2,False,3,3,1,2,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,0,4,5,22,11,72148,1,1905.88,365,True,...,False,True,151,0,True,1,2,0,1,43
14996,1,4,5,23,1,71046,4,104.37,365,False,...,False,True,111,0,False,6,6,5,0,2
14997,0,5,1,21,4,36415,3,24.32,180,False,...,True,True,46,1,False,12,12,1,2,8
14998,1,1,6,11,4,93000,4,98.04,90,False,...,False,True,143,2,False,10,10,1,4,10
14999,0,2,4,22,9,29881,3,5639.79,365,True,...,False,True,218,4,False,10,10,4,1,18

## Create the Target (y)

In [5]:
y = claims["Claim_Status"]

## Claim_Status is still text (Approved / Denied), we'll encode

In [6]:
from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

In [8]:
print(dict(zip(target_encoder.classes_,
               target_encoder.transform(target_encoder.classes_))))

{'Approved': np.int64(0), 'Denied': np.int64(1)}

In [11]:
joblib.dump(target_encoder, "target_encoder.pkl")

['target_encoder.pkl']

In [12]:
import joblib

joblib.dump(target_encoder, "target_encoder.pkl")

print("Target encoder saved successfully!")

Target encoder saved successfully!